[settings]
default='localtest'
; PDO error modes: ERRMODE_SILENT = 0; ERRMODE_WARNING = 1; ERRMODE_EXCEPTION = 2;
; errormode=2
[localtest]
; server= defaults to localhost
database=localtest
user=twoquake_songs
pwd='t5apRisoWrUT!NAYUw0w'

[production]
; server= defaults to localhost
database=twoquake_pnut25
user=twoquake_songs
pwd='t5apRisoWrUT!NAYUw0w'

[nutshell]
; server= defaults to localhost
database=twoquake_songs_2
user=twoquake_songs
pwd='t5apRisoWrUT!NAYUw0w'

[twoq]
database=twoquake_net
user=twoquake_net
pwd='h%;puaAm#yJ~'

[test]
server=testserver
database=testdb
user=(user name here)
pwd=(password here)